import React, { useEffect, useState } from 'react';
import { api } from '../../lib/api';
import { Button, Card, CardContent, CardHeader, CardTitle, Input, PageHeader, Select, Textarea } from '../../components/ui';

const emptyIncident = { title: '', severity: 'medium', detectedAt: new Date().toISOString().slice(0, 10), description: '', actions: '' };

export default function Compliance() {
  const [requests, setRequests] = useState([]); const [incidents, setIncidents] = useState([]); const [settings, setSettings] = useState({});
  const [incident, setIncident] = useState(emptyIncident); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const load = async () => { try { const [r, i, s] = await Promise.all([api.get('/legalRequests'), api.get('/securityIncidents'), api.get('/settings/mine')]); setRequests(r || []); setIncidents(i || []); setSettings(s || {}); } catch (e) { setMessage(e.message); } };
  useEffect(() => { load(); }, []);
  const legal = settings.legalProfile || {};
  const saveRetention = async (e) => { e.preventDefault(); setSaving(true); try { await api.put('/settings', { legalProfile: { ...legal, privacyNoticeVersion: legal.privacyNoticeVersion || 'DRAFT-1', termsVersion: legal.termsVersion || 'DRAFT-1', policyEffectiveDate: legal.policyEffectiveDate || new Date().toISOString().slice(0, 10), patientRecordRetentionYears: Number(legal.patientRecordRetentionYears) || 3, invoiceRetentionYears: Number(legal.invoiceRetentionYears) || 8, messageRetentionDays: Number(legal.messageRetentionDays) || 365, securityLogRetentionDays: Number(legal.securityLogRetentionDays) || 180 } }); setMessage('Compliance settings saved.'); await load(); } catch (e) { setMessage(e.message); } finally { setSaving(false); } };
  const createIncident = async (e) => { e.preventDefault(); setSaving(true); try { await api.post('/securityIncidents', { ...incident, status: 'Open', timeline: [], notifiedAt: null, closedAt: null }); setIncident(emptyIncident); setMessage('Incident recorded. Follow the response plan and document each action.'); await load(); } catch (e) { setMessage(e.message); } finally { setSaving(false); } };
  const updateRequest = async (item, status) => { try { await api.put(`/legalRequests/${item.id}`, { status, resolvedAt: status === 'Resolved' ? new Date().toISOString() : null }); await load(); } catch (e) { setMessage(e.message); } };
  return <div className="space-y-6 pb-12"><PageHeader title="Legal & Compliance" subtitle="Patient rights, retention, incidents, and clinic policy configuration" />
    {message && <div className="rounded-md border bg-muted p-3 text-sm">{message}</div>}
    <Card><CardHeader><CardTitle>Policy and retention settings</CardTitle></CardHeader><CardContent><form onSubmit={saveRetention} className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><div><label className="mb-1 block text-xs text-muted-foreground">Privacy notice version</label><Input value={legal.privacyNoticeVersion || ''} onChange={(e) => setSettings({ ...settings, legalProfile: { ...legal, privacyNoticeVersion: e.target.value } })} placeholder="2026-09-06-v1" /></div><div><label className="mb-1 block text-xs text-muted-foreground">Terms version</label><Input value={legal.termsVersion || ''} onChange={(e) => setSettings({ ...settings, legalProfile: { ...legal, termsVersion: e.target.value } })} placeholder="2026-09-06-v1" /></div><div><label className="mb-1 block text-xs text-muted-foreground">Clinical records (years)</label><Input type="number" min="1" value={legal.patientRecordRetentionYears || 3} onChange={(e) => setSettings({ ...settings, legalProfile: { ...legal, patientRecordRetentionYears: e.target.value } })} /></div><div><label className="mb-1 block text-xs text-muted-foreground">Invoices (years)</label><Input type="number" min="1" value={legal.invoiceRetentionYears || 8} onChange={(e) => setSettings({ ...settings, legalProfile: { ...legal, invoiceRetentionYears: e.target.value } })} /></div><div><label className="mb-1 block text-xs text-muted-foreground">Messages (days)</label><Input type="number" min="1" value={legal.messageRetentionDays || 365} onChange={(e) => setSettings({ ...settings, legalProfile: { ...legal, messageRetentionDays: e.target.value } })} /></div><div><label className="mb-1 block text-xs text-muted-foreground">Security logs (days)</label><Input type="number" min="180" value={legal.securityLogRetentionDays || 180} onChange={(e) => setSettings({ ...settings, legalProfile: { ...legal, securityLogRetentionDays: e.target.value } })} /></div><div className="md:col-span-2 flex items-end"><Button disabled={saving}>{saving ? 'Saving...' : 'Save policy settings'}</Button></div></form><p className="mt-4 text-xs text-muted-foreground">These are policy configuration values, not legal advice. Confirm retention periods with the clinic’s lawyer/CA before production use.</p></CardContent></Card>
    <Card><CardHeader><CardTitle>Patient data-rights requests ({requests.length})</CardTitle></CardHeader><CardContent className="space-y-3">{requests.length === 0 ? <p className="text-sm text-muted-foreground">No requests received.</p> : requests.map((r) => <div key={r.id} className="rounded-md border p-4"><div className="flex flex-wrap justify-between gap-2"><p className="font-medium">{r.type} · {r.name}</p><span className="text-xs text-muted-foreground">{r.status}</span></div><p className="text-sm text-muted-foreground">{r.email} {r.phone ? `· ${r.phone}` : ''}</p><p className="mt-2 text-sm">{r.details || 'No extra details.'}</p><div className="mt-3 flex gap-2"><Button size="sm" variant="outline" onClick={() => updateRequest(r, 'In Review')}>Mark in review</Button><Button size="sm" onClick={() => updateRequest(r, 'Resolved')}>Mark resolved</Button></div></div>)}</CardContent></Card>
    <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Record a security incident</CardTitle></CardHeader><CardContent><form onSubmit={createIncident} className="space-y-3"><Input required placeholder="Short incident title" value={incident.title} onChange={(e) => setIncident({ ...incident, title: e.target.value })} /><Select value={incident.severity} onChange={(e) => setIncident({ ...incident, severity: e.target.value })}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></Select><Input type="date" value={incident.detectedAt} onChange={(e) => setIncident({ ...incident, detectedAt: e.target.value })} /><Textarea required rows={3} placeholder="What happened? Do not paste passwords or tokens." value={incident.description} onChange={(e) => setIncident({ ...incident, description: e.target.value })} /><Textarea rows={3} placeholder="Containment and immediate actions" value={incident.actions} onChange={(e) => setIncident({ ...incident, actions: e.target.value })} /><Button disabled={saving}>Record incident</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Incident register ({incidents.length})</CardTitle></CardHeader><CardContent className="space-y-3">{incidents.length === 0 ? <p className="text-sm text-muted-foreground">No incidents recorded.</p> : incidents.map((i) => <div key={i.id} className="rounded-md border p-3"><div className="flex justify-between"><strong>{i.title}</strong><span className="text-xs text-muted-foreground">{i.severity} · {i.status}</span></div><p className="text-xs text-muted-foreground">Detected {i.detectedAt}</p><p className="mt-2 text-sm">{i.description}</p></div>)}</CardContent></Card></div>
  </div>;
}
